// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as inputs from "./types/input";
import * as outputs from "./types/output";
import * as utilities from "./utilities";

/**
 * Use this data source to get a Sonarqube qualitygate resource
 *
 * ## Example Usage
 *
 * ```typescript
 * import * as pulumi from "@pulumi/pulumi";
 * import * as sonarqube from "@pulumi/sonarqube";
 *
 * const main = sonarqube.getQualitygate({
 *     name: "example",
 * });
 * ```
 */
export function getQualitygate(args: GetQualitygateArgs, opts?: pulumi.InvokeOptions): Promise<GetQualitygateResult> {
    opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts || {});
    return pulumi.runtime.invoke("sonarqube:index/getQualitygate:getQualitygate", {
        "name": args.name,
    }, opts);
}

/**
 * A collection of arguments for invoking getQualitygate.
 */
export interface GetQualitygateArgs {
    /**
     * The name of the Quality Gate.
     */
    name: string;
}

/**
 * A collection of values returned by getQualitygate.
 */
export interface GetQualitygateResult {
    /**
     * List of Quality Gate conditions.
     */
    readonly conditions: outputs.GetQualitygateCondition[];
    /**
     * Origin of the Quality Gate
     */
    readonly copyFrom: string;
    /**
     * The provider-assigned unique ID for this managed resource.
     */
    readonly id: string;
    /**
     * Quality Gate default.
     */
    readonly isDefault: boolean;
    /**
     * The name of the Quality Gate.
     */
    readonly name: string;
}
/**
 * Use this data source to get a Sonarqube qualitygate resource
 *
 * ## Example Usage
 *
 * ```typescript
 * import * as pulumi from "@pulumi/pulumi";
 * import * as sonarqube from "@pulumi/sonarqube";
 *
 * const main = sonarqube.getQualitygate({
 *     name: "example",
 * });
 * ```
 */
export function getQualitygateOutput(args: GetQualitygateOutputArgs, opts?: pulumi.InvokeOutputOptions): pulumi.Output<GetQualitygateResult> {
    opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts || {});
    return pulumi.runtime.invokeOutput("sonarqube:index/getQualitygate:getQualitygate", {
        "name": args.name,
    }, opts);
}

/**
 * A collection of arguments for invoking getQualitygate.
 */
export interface GetQualitygateOutputArgs {
    /**
     * The name of the Quality Gate.
     */
    name: pulumi.Input<string>;
}
