// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as utilities from "./utilities";

/**
 * Provides a Sonarqube GitHub binding resource. This can be used to create and manage the binding between a
 * GitHub repository and a SonarQube project
 *
 * ## Example Usage
 *
 * ```typescript
 * import * as pulumi from "@pulumi/pulumi";
 * import * as sonarqube from "@pulumi/sonarqube";
 *
 * const github_alm = new sonarqube.AlmGithub("github-alm", {
 *     appId: "12345",
 *     clientId: "56789",
 *     clientSecret: "secret",
 *     key: "myalm",
 *     privateKey: "myprivate_key",
 *     url: "https://api.github.com",
 *     webhookSecret: "mysecret",
 * });
 * const main = new sonarqube.Project("main", {
 *     project: "my_project",
 *     visibility: "public",
 * });
 * const github_binding = new sonarqube.GithubBinding("github-binding", {
 *     almSetting: github_alm.key,
 *     project: "my_project",
 *     repository: "myorg/myrepo",
 * });
 * ```
 */
export class GithubBinding extends pulumi.CustomResource {
    /**
     * Get an existing GithubBinding resource's state with the given name, ID, and optional extra
     * properties used to qualify the lookup.
     *
     * @param name The _unique_ name of the resulting resource.
     * @param id The _unique_ provider ID of the resource to lookup.
     * @param state Any extra arguments used during the lookup.
     * @param opts Optional settings to control the behavior of the CustomResource.
     */
    public static get(name: string, id: pulumi.Input<pulumi.ID>, state?: GithubBindingState, opts?: pulumi.CustomResourceOptions): GithubBinding {
        return new GithubBinding(name, <any>state, { ...opts, id: id });
    }

    /** @internal */
    public static readonly __pulumiType = 'sonarqube:index/githubBinding:GithubBinding';

    /**
     * Returns true if the given object is an instance of GithubBinding.  This is designed to work even
     * when multiple copies of the Pulumi SDK have been loaded into the same process.
     */
    public static isInstance(obj: any): obj is GithubBinding {
        if (obj === undefined || obj === null) {
            return false;
        }
        return obj['__pulumiType'] === GithubBinding.__pulumiType;
    }

    /**
     * GitHub ALM setting key
     */
    public readonly almSetting!: pulumi.Output<string>;
    /**
     * Is this project part of a monorepo. Default value: false
     */
    public readonly monorepo!: pulumi.Output<string | undefined>;
    /**
     * Project key
     */
    public readonly project!: pulumi.Output<string>;
    /**
     * The full name of your GitHub repository, including the organization, case-sensitive. Maximum length: 256
     */
    public readonly repository!: pulumi.Output<string>;
    /**
     * Enable/disable summary in PR discussion tab. Default value: true
     */
    public readonly summaryCommentEnabled!: pulumi.Output<string | undefined>;

    /**
     * Create a GithubBinding resource with the given unique name, arguments, and options.
     *
     * @param name The _unique_ name of the resource.
     * @param args The arguments to use to populate this resource's properties.
     * @param opts A bag of options that control this resource's behavior.
     */
    constructor(name: string, args: GithubBindingArgs, opts?: pulumi.CustomResourceOptions)
    constructor(name: string, argsOrState?: GithubBindingArgs | GithubBindingState, opts?: pulumi.CustomResourceOptions) {
        let resourceInputs: pulumi.Inputs = {};
        opts = opts || {};
        if (opts.id) {
            const state = argsOrState as GithubBindingState | undefined;
            resourceInputs["almSetting"] = state ? state.almSetting : undefined;
            resourceInputs["monorepo"] = state ? state.monorepo : undefined;
            resourceInputs["project"] = state ? state.project : undefined;
            resourceInputs["repository"] = state ? state.repository : undefined;
            resourceInputs["summaryCommentEnabled"] = state ? state.summaryCommentEnabled : undefined;
        } else {
            const args = argsOrState as GithubBindingArgs | undefined;
            if ((!args || args.almSetting === undefined) && !opts.urn) {
                throw new Error("Missing required property 'almSetting'");
            }
            if ((!args || args.project === undefined) && !opts.urn) {
                throw new Error("Missing required property 'project'");
            }
            if ((!args || args.repository === undefined) && !opts.urn) {
                throw new Error("Missing required property 'repository'");
            }
            resourceInputs["almSetting"] = args ? args.almSetting : undefined;
            resourceInputs["monorepo"] = args ? args.monorepo : undefined;
            resourceInputs["project"] = args ? args.project : undefined;
            resourceInputs["repository"] = args ? args.repository : undefined;
            resourceInputs["summaryCommentEnabled"] = args ? args.summaryCommentEnabled : undefined;
        }
        opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts);
        super(GithubBinding.__pulumiType, name, resourceInputs, opts);
    }
}

/**
 * Input properties used for looking up and filtering GithubBinding resources.
 */
export interface GithubBindingState {
    /**
     * GitHub ALM setting key
     */
    almSetting?: pulumi.Input<string>;
    /**
     * Is this project part of a monorepo. Default value: false
     */
    monorepo?: pulumi.Input<string>;
    /**
     * Project key
     */
    project?: pulumi.Input<string>;
    /**
     * The full name of your GitHub repository, including the organization, case-sensitive. Maximum length: 256
     */
    repository?: pulumi.Input<string>;
    /**
     * Enable/disable summary in PR discussion tab. Default value: true
     */
    summaryCommentEnabled?: pulumi.Input<string>;
}

/**
 * The set of arguments for constructing a GithubBinding resource.
 */
export interface GithubBindingArgs {
    /**
     * GitHub ALM setting key
     */
    almSetting: pulumi.Input<string>;
    /**
     * Is this project part of a monorepo. Default value: false
     */
    monorepo?: pulumi.Input<string>;
    /**
     * Project key
     */
    project: pulumi.Input<string>;
    /**
     * The full name of your GitHub repository, including the organization, case-sensitive. Maximum length: 256
     */
    repository: pulumi.Input<string>;
    /**
     * Enable/disable summary in PR discussion tab. Default value: true
     */
    summaryCommentEnabled?: pulumi.Input<string>;
}
