// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as utilities from "./utilities";

/**
 * Provides a Sonarqube Webhook resource. This can be used to manage Sonarqube webhooks.
 *
 * ## Example Usage
 *
 * ### Example: create a webhook
 * ```typescript
 * import * as pulumi from "@pulumi/pulumi";
 * import * as sonarqube from "@pulumi/sonarqube";
 *
 * const webhook = new sonarqube.Webhook("webhook", {url: "https://my-webhook-destination.example.com"});
 * ```
 *
 * ### Example: create a webhook owned by a project
 * ```typescript
 * import * as pulumi from "@pulumi/pulumi";
 * import * as sonarqube from "@pulumi/sonarqube";
 *
 * const project = new sonarqube.Project("project", {
 *     project: "project",
 *     visibility: "public",
 * });
 * const webhook = new sonarqube.Webhook("webhook", {
 *     url: "https://my-webhook-destination.example.com",
 *     project: project.name,
 * });
 * ```
 */
export class Webhook extends pulumi.CustomResource {
    /**
     * Get an existing Webhook resource's state with the given name, ID, and optional extra
     * properties used to qualify the lookup.
     *
     * @param name The _unique_ name of the resulting resource.
     * @param id The _unique_ provider ID of the resource to lookup.
     * @param state Any extra arguments used during the lookup.
     * @param opts Optional settings to control the behavior of the CustomResource.
     */
    public static get(name: string, id: pulumi.Input<pulumi.ID>, state?: WebhookState, opts?: pulumi.CustomResourceOptions): Webhook {
        return new Webhook(name, <any>state, { ...opts, id: id });
    }

    /** @internal */
    public static readonly __pulumiType = 'sonarqube:index/webhook:Webhook';

    /**
     * Returns true if the given object is an instance of Webhook.  This is designed to work even
     * when multiple copies of the Pulumi SDK have been loaded into the same process.
     */
    public static isInstance(obj: any): obj is Webhook {
        if (obj === undefined || obj === null) {
            return false;
        }
        return obj['__pulumiType'] === Webhook.__pulumiType;
    }

    /**
     * The name of the webhook to create. This will be displayed in the Sonarqube administration console.
     */
    public readonly name!: pulumi.Output<string>;
    /**
     * The key of the project that will own the webhook.
     */
    public readonly project!: pulumi.Output<string | undefined>;
    /**
     * The secret to send with the event payload.
     */
    public readonly secret!: pulumi.Output<string>;
    /**
     * The URL to send event payloads to. This must begin with either `https://` or `http://`.
     */
    public readonly url!: pulumi.Output<string>;

    /**
     * Create a Webhook resource with the given unique name, arguments, and options.
     *
     * @param name The _unique_ name of the resource.
     * @param args The arguments to use to populate this resource's properties.
     * @param opts A bag of options that control this resource's behavior.
     */
    constructor(name: string, args: WebhookArgs, opts?: pulumi.CustomResourceOptions)
    constructor(name: string, argsOrState?: WebhookArgs | WebhookState, opts?: pulumi.CustomResourceOptions) {
        let resourceInputs: pulumi.Inputs = {};
        opts = opts || {};
        if (opts.id) {
            const state = argsOrState as WebhookState | undefined;
            resourceInputs["name"] = state ? state.name : undefined;
            resourceInputs["project"] = state ? state.project : undefined;
            resourceInputs["secret"] = state ? state.secret : undefined;
            resourceInputs["url"] = state ? state.url : undefined;
        } else {
            const args = argsOrState as WebhookArgs | undefined;
            if ((!args || args.url === undefined) && !opts.urn) {
                throw new Error("Missing required property 'url'");
            }
            resourceInputs["name"] = args ? args.name : undefined;
            resourceInputs["project"] = args ? args.project : undefined;
            resourceInputs["secret"] = args?.secret ? pulumi.secret(args.secret) : undefined;
            resourceInputs["url"] = args ? args.url : undefined;
        }
        opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts);
        const secretOpts = { additionalSecretOutputs: ["secret"] };
        opts = pulumi.mergeOptions(opts, secretOpts);
        super(Webhook.__pulumiType, name, resourceInputs, opts);
    }
}

/**
 * Input properties used for looking up and filtering Webhook resources.
 */
export interface WebhookState {
    /**
     * The name of the webhook to create. This will be displayed in the Sonarqube administration console.
     */
    name?: pulumi.Input<string>;
    /**
     * The key of the project that will own the webhook.
     */
    project?: pulumi.Input<string>;
    /**
     * The secret to send with the event payload.
     */
    secret?: pulumi.Input<string>;
    /**
     * The URL to send event payloads to. This must begin with either `https://` or `http://`.
     */
    url?: pulumi.Input<string>;
}

/**
 * The set of arguments for constructing a Webhook resource.
 */
export interface WebhookArgs {
    /**
     * The name of the webhook to create. This will be displayed in the Sonarqube administration console.
     */
    name?: pulumi.Input<string>;
    /**
     * The key of the project that will own the webhook.
     */
    project?: pulumi.Input<string>;
    /**
     * The secret to send with the event payload.
     */
    secret?: pulumi.Input<string>;
    /**
     * The URL to send event payloads to. This must begin with either `https://` or `http://`.
     */
    url: pulumi.Input<string>;
}
